--- #YAML:1.0
name: JQuery-Mobile
version: 0.03
author:
  - Xufeng (Danny) Liang <danny.glue@gmail.com>
abstract: Interface to jQuery Mobile
license: perl
requires:
  Test::More: 0
  HTML::Entities: 0
  Clone: 0
  Exporter: 5.57
